name: Codeberg sync
on:
  workflow_dispatch:

jobs:
  call-codeberg-sync:
    if: ${{ secrets.CODEBERG_TOKEN != '' }}
    continue-on-error: true
    uses: arpanghosh8453/codeberg-sync/.github/workflows/codeberg-sync.yml@main
    secrets:
      CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
